services:
  frontend-quote-generator:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true